### PR TITLE
Drew Navbar / Pages / Links / Button / Login/ Logout update

### PR DESCRIPTION
**Pull request by Robbins180**

### CODE REVIEW

**Comment by Robbins180** [comment]
.

**Comment by uzoway** [comment]
You can merge the PR to the master branch since there are no conflicts.

**Comment by Robbins180** [comment]
An update for App.js Setup with routes and paths
Updated Navbar.js/css Login.js
Logout.js
Button.js/css
pages & routes
index.js

**Comment by Robbins180** [comment]
Merge conflicts fixed in Readme

**Pull request merged**
